const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  // editIf: state => state.notice.editIf,
  // noticeIfRead: state => state.notice.noticeIfRead,
  // noticeId: state => state.notice.noticeId,
  // noticePublish: state => state.notice.noticePublish,
  // noticeTitle: state => state.notice.noticeTitle,
  // noticeContent: state => state.notice.noticeContent,
  // noticeReadNum: state => state.notice.noticeReadNum,
  // noticeStatus: state => state.notice.noticeStatus,
  getNotice: state => state.noticeList,
  getCount: state => state.count
}
export default getters
